"""initial schema

Revision ID: 4018c66f8af5
Revises: 
Create Date: 2026-10-01 23:58:29.669803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4018c66f8af5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('primary_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', name='uq_source_documents_accession_number')
    )
    op.create_index('ix_source_documents_ticker_fiscal_year', 'source_documents', ['ticker', 'fiscal_year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_threads_user_id', 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_chunk')
    )
    op.create_index('ix_document_chunks_chunk_metadata_gin', 'document_chunks', ['chunk_metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_search_vector_gin', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('document_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('units', sa.String(length=255), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_html_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'table_index', name='uq_document_tables_document_table')
    )
    op.create_index('ix_document_tables_document_id', 'document_tables', ['document_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'sequence', name='uq_chat_messages_thread_sequence')
    )
    op.create_index('ix_chat_messages_thread_id', 'chat_messages', ['thread_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'citation_index', name='uq_message_citations_message_citation_index')
    )
    op.create_index('ix_message_citations_message_id', 'message_citations', ['message_id'], unique=False)
    # ### end Alembic commands ###
    _enable_rls_and_policies()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_citations_message_id', table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index('ix_chat_messages_thread_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_document_tables_document_id', table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index('ix_document_chunks_search_vector_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_chunk_metadata_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    op.drop_index('ix_chat_threads_user_id', table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_table('users')
    op.drop_index('ix_source_documents_ticker_fiscal_year', table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
    _drop_rls_and_policies()

_THREAD_OWNED = """
    EXISTS (
        SELECT 1 FROM chat_threads
        WHERE chat_threads.id = chat_messages.thread_id
          AND chat_threads.user_id = auth.uid()
    )
"""

_MESSAGE_OWNED = """
    EXISTS (
        SELECT 1 FROM chat_messages
        JOIN chat_threads ON chat_threads.id = chat_messages.thread_id
        WHERE chat_messages.id = message_citations.message_id
          AND chat_threads.user_id = auth.uid()
    )
"""

RLS_TABLES = (
    "users",
    "source_documents",
    "document_tables",
    "document_chunks",
    "chat_threads",
    "chat_messages",
    "message_citations",
)

# (table, policy name, policy clause)
POLICIES = (
    ("users", "users_select_own",
     "FOR SELECT TO authenticated USING (auth.uid() = id)"),
    ("users", "users_update_own",
     "FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id)"),

    ("source_documents", "source_documents_select_authenticated",
     "FOR SELECT TO authenticated USING (true)"),
    ("document_tables", "document_tables_select_authenticated",
     "FOR SELECT TO authenticated USING (true)"),
    ("document_chunks", "document_chunks_select_authenticated",
     "FOR SELECT TO authenticated USING (true)"),

    ("chat_threads", "chat_threads_select_own",
     "FOR SELECT TO authenticated USING (auth.uid() = user_id)"),
    ("chat_threads", "chat_threads_insert_own",
     "FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id)"),
    ("chat_threads", "chat_threads_update_own",
     "FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)"),
    ("chat_threads", "chat_threads_delete_own",
     "FOR DELETE TO authenticated USING (auth.uid() = user_id)"),

    ("chat_messages", "chat_messages_select_own",
     f"FOR SELECT TO authenticated USING ({_THREAD_OWNED})"),
    ("chat_messages", "chat_messages_insert_own",
     f"FOR INSERT TO authenticated WITH CHECK ({_THREAD_OWNED})"),
    ("chat_messages", "chat_messages_update_own",
     f"FOR UPDATE TO authenticated USING ({_THREAD_OWNED}) WITH CHECK ({_THREAD_OWNED})"),
    ("chat_messages", "chat_messages_delete_own",
     f"FOR DELETE TO authenticated USING ({_THREAD_OWNED})"),

    ("message_citations", "message_citations_select_own",
     f"FOR SELECT TO authenticated USING ({_MESSAGE_OWNED})"),
    ("message_citations", "message_citations_insert_own",
     f"FOR INSERT TO authenticated WITH CHECK ({_MESSAGE_OWNED})"),
    ("message_citations", "message_citations_delete_own",
     f"FOR DELETE TO authenticated USING ({_MESSAGE_OWNED})"),
)


def _enable_rls_and_policies() -> None:
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    for table, name, clause in POLICIES:
        op.execute(f"CREATE POLICY {name} ON {table} {clause}")


def _drop_rls_and_policies() -> None:
    for table, name, _ in reversed(POLICIES):
        op.execute(f"DROP POLICY IF EXISTS {name} ON {table}")
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")